# Site settings
title: Make Store Catalogues Easy.
email: al@atlastechnologies.xyz
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getstorecat.com/" # the base hostname & protocol for your site

twitter_username: storecat

# Build settings
markdown: kramdown

collections_dir: _collections/

collections:
  docs: 
    layout: individualDoc
    output: true  
  integrations: 
    layout: integration
    output: true  
  extensions: 
    layout: extension
    output: true          

defaults:
  - scope:
      path: ""
    values:
      layout: "default"